export const REQUEST_FEATURES = "REQUEST_FEATURES";
export const RECEIVE_FEATURES = "RECEIVE_FEATURES";

export const REQUEST_POINT_DETAIL = "REQUEST_POINT_DETAIL";
export const RECEIVE_POINT_DETAIL = "RECEIVE_POINT_DETAIL";
